GRUMPLE_NODE_ROLE_UNDEFINED = 'UNDEFINED'
GRUMPLE_NODE_ROLE_CLIENT = 'CLIENT'
GRUMPLE_NODE_ROLE_ROUTER = 'ROUTER'
GRUMPLE_NODE_ROLE_OSS = 'OSS'
GRUMPLE_NODE_ROLE_OST = 'OST'
GRUMPLE_NODE_ROLE_MGS = 'MGS'
GRUMPLE_NODE_ROLE_MDT = 'MDT'
GRUMPLE_NODE_ROLE_MDS = 'MDS'
GRUMPLE_NODE_ROLE_MGT = 'MGT'


