

/*
 * Copyright (C) 2011 FUJITSU LIMITED.  All rights reserved.
 *
 * Copyright (c) 2013, Intel Corporation.
 */

#include <grumple_errno.h>

#ifdef GRUMPLE_TRANSLATE_ERRNOS
#include <grumple_dlm.h>

/*
 * The two translation tables below must define a one-to-one mapping between
 * host and network errnos.
 *
 * EAGAIN is equal to EAGAIN on all architectures except for parisc, which
 * appears irrelevant.  Thus, existing references to EAGAIN are fine.
 *
 * EDEADLOCK is equal to EDEADLK on x86 but not on sparc, at least.  A sparc
 * host has no context-free way to determine if a GRUMPLE_EDEADLK represents an
 * EDEADLK or an EDEADLOCK.  Therefore, all existing references to EDEADLOCK
 * that need to be transferred on wire have been replaced with EDEADLK.
 */
static int grumple_errno_hton_mapping[] = {
	[EPERM]			= GRUMPLE_EPERM,
	[ENOENT]		= GRUMPLE_ENOENT,
	[ESRCH]			= GRUMPLE_ESRCH,
	[EINTR]			= GRUMPLE_EINTR,
	[EIO]			= GRUMPLE_EIO,
	[ENXIO]			= GRUMPLE_ENXIO,
	[E2BIG]			= GRUMPLE_E2BIG,
	[ENOEXEC]		= GRUMPLE_ENOEXEC,
	[EBADF]			= GRUMPLE_EBADF,
	[ECHILD]		= GRUMPLE_ECHILD,
	[EAGAIN]		= GRUMPLE_EAGAIN,
	[ENOMEM]		= GRUMPLE_ENOMEM,
	[EACCES]		= GRUMPLE_EACCES,
	[EFAULT]		= GRUMPLE_EFAULT,
	[ENOTBLK]		= GRUMPLE_ENOTBLK,
	[EBUSY]			= GRUMPLE_EBUSY,
	[EEXIST]		= GRUMPLE_EEXIST,
	[EXDEV]			= GRUMPLE_EXDEV,
	[ENODEV]		= GRUMPLE_ENODEV,
	[ENOTDIR]		= GRUMPLE_ENOTDIR,
	[EISDIR]		= GRUMPLE_EISDIR,
	[EINVAL]		= GRUMPLE_EINVAL,
	[ENFILE]		= GRUMPLE_ENFILE,
	[EMFILE]		= GRUMPLE_EMFILE,
	[ENOTTY]		= GRUMPLE_ENOTTY,
	[ETXTBSY]		= GRUMPLE_ETXTBSY,
	[EFBIG]			= GRUMPLE_EFBIG,
	[ENOSPC]		= GRUMPLE_ENOSPC,
	[ESPIPE]		= GRUMPLE_ESPIPE,
	[EROFS]			= GRUMPLE_EROFS,
	[EMLINK]		= GRUMPLE_EMLINK,
	[EPIPE]			= GRUMPLE_EPIPE,
	[EDOM]			= GRUMPLE_EDOM,
	[ERANGE]		= GRUMPLE_ERANGE,
	[EDEADLK]		= GRUMPLE_EDEADLK,
	[ENAMETOOLONG]		= GRUMPLE_ENAMETOOLONG,
	[ENOLCK]		= GRUMPLE_ENOLCK,
	[ENOSYS]		= GRUMPLE_ENOSYS,
	[ENOTEMPTY]		= GRUMPLE_ENOTEMPTY,
	[ELOOP]			= GRUMPLE_ELOOP,
	[ENOMSG]		= GRUMPLE_ENOMSG,
	[EIDRM]			= GRUMPLE_EIDRM,
	[ECHRNG]		= GRUMPLE_ECHRNG,
	[EL2NSYNC]		= GRUMPLE_EL2NSYNC,
	[EL3HLT]		= GRUMPLE_EL3HLT,
	[EL3RST]		= GRUMPLE_EL3RST,
	[ELNRNG]		= GRUMPLE_ELNRNG,
	[EUNATCH]		= GRUMPLE_EUNATCH,
	[ENOCSI]		= GRUMPLE_ENOCSI,
	[EL2HLT]		= GRUMPLE_EL2HLT,
	[EBADE]			= GRUMPLE_EBADE,
	[EBADR]			= GRUMPLE_EBADR,
	[EXFULL]		= GRUMPLE_EXFULL,
	[ENOANO]		= GRUMPLE_ENOANO,
	[EBADRQC]		= GRUMPLE_EBADRQC,
	[EBADSLT]		= GRUMPLE_EBADSLT,
	[EBFONT]		= GRUMPLE_EBFONT,
	[ENOSTR]		= GRUMPLE_ENOSTR,
	[ENODATA]		= GRUMPLE_ENODATA,
	[ETIME]			= GRUMPLE_ETIME,
	[ENOSR]			= GRUMPLE_ENOSR,
	[ENONET]		= GRUMPLE_ENONET,
	[ENOPKG]		= GRUMPLE_ENOPKG,
	[EREMOTE]		= GRUMPLE_EREMOTE,
	[ENOLINK]		= GRUMPLE_ENOLINK,
	[EADV]			= GRUMPLE_EADV,
	[ESRMNT]		= GRUMPLE_ESRMNT,
	[ECOMM]			= GRUMPLE_ECOMM,
	[EPROTO]		= GRUMPLE_EPROTO,
	[EMULTIHOP]		= GRUMPLE_EMULTIHOP,
	[EDOTDOT]		= GRUMPLE_EDOTDOT,
	[EBADMSG]		= GRUMPLE_EBADMSG,
	[EOVERFLOW]		= GRUMPLE_EOVERFLOW,
	[ENOTUNIQ]		= GRUMPLE_ENOTUNIQ,
	[EBADFD]		= GRUMPLE_EBADFD,
	[EREMCHG]		= GRUMPLE_EREMCHG,
	[ELIBACC]		= GRUMPLE_ELIBACC,
	[ELIBBAD]		= GRUMPLE_ELIBBAD,
	[ELIBSCN]		= GRUMPLE_ELIBSCN,
	[ELIBMAX]		= GRUMPLE_ELIBMAX,
	[ELIBEXEC]		= GRUMPLE_ELIBEXEC,
	[EILSEQ]		= GRUMPLE_EILSEQ,
	[ERESTART]		= GRUMPLE_ERESTART,
	[ESTRPIPE]		= GRUMPLE_ESTRPIPE,
	[EUSERS]		= GRUMPLE_EUSERS,
	[ENOTSOCK]		= GRUMPLE_ENOTSOCK,
	[EDESTADDRREQ]		= GRUMPLE_EDESTADDRREQ,
	[EMSGSIZE]		= GRUMPLE_EMSGSIZE,
	[EPROTOTYPE]		= GRUMPLE_EPROTOTYPE,
	[ENOPROTOOPT]		= GRUMPLE_ENOPROTOOPT,
	[EPROTONOSUPPORT]	= GRUMPLE_EPROTONOSUPPORT,
	[ESOCKTNOSUPPORT]	= GRUMPLE_ESOCKTNOSUPPORT,
	[EOPNOTSUPP]		= GRUMPLE_EOPNOTSUPP,
	[EPFNOSUPPORT]		= GRUMPLE_EPFNOSUPPORT,
	[EAFNOSUPPORT]		= GRUMPLE_EAFNOSUPPORT,
	[EADDRINUSE]		= GRUMPLE_EADDRINUSE,
	[EADDRNOTAVAIL]		= GRUMPLE_EADDRNOTAVAIL,
	[ENETDOWN]		= GRUMPLE_ENETDOWN,
	[ENETUNREACH]		= GRUMPLE_ENETUNREACH,
	[ENETRESET]		= GRUMPLE_ENETRESET,
	[ECONNABORTED]		= GRUMPLE_ECONNABORTED,
	[ECONNRESET]		= GRUMPLE_ECONNRESET,
	[ENOBUFS]		= GRUMPLE_ENOBUFS,
	[EISCONN]		= GRUMPLE_EISCONN,
	[ENOTCONN]		= GRUMPLE_ENOTCONN,
	[ESHUTDOWN]		= GRUMPLE_ESHUTDOWN,
	[ETOOMANYREFS]		= GRUMPLE_ETOOMANYREFS,
	[ETIMEDOUT]		= GRUMPLE_ETIMEDOUT,
	[ECONNREFUSED]		= GRUMPLE_ECONNREFUSED,
	[EHOSTDOWN]		= GRUMPLE_EHOSTDOWN,
	[EHOSTUNREACH]		= GRUMPLE_EHOSTUNREACH,
	[EALREADY]		= GRUMPLE_EALREADY,
	[EINPROGRESS]		= GRUMPLE_EINPROGRESS,
	[ESTALE]		= GRUMPLE_ESTALE,
	[EUCLEAN]		= GRUMPLE_EUCLEAN,
	[ENOTNAM]		= GRUMPLE_ENOTNAM,
	[ENAVAIL]		= GRUMPLE_ENAVAIL,
	[EISNAM]		= GRUMPLE_EISNAM,
	[EREMOTEIO]		= GRUMPLE_EREMOTEIO,
	[EDQUOT]		= GRUMPLE_EDQUOT,
	[ENOMEDIUM]		= GRUMPLE_ENOMEDIUM,
	[EMEDIUMTYPE]		= GRUMPLE_EMEDIUMTYPE,
	[ECANCELED]		= GRUMPLE_ECANCELED,
	[ENOKEY]		= GRUMPLE_ENOKEY,
	[EKEYEXPIRED]		= GRUMPLE_EKEYEXPIRED,
	[EKEYREVOKED]		= GRUMPLE_EKEYREVOKED,
	[EKEYREJECTED]		= GRUMPLE_EKEYREJECTED,
	[EOWNERDEAD]		= GRUMPLE_EOWNERDEAD,
	[ENOTRECOVERABLE]	= GRUMPLE_ENOTRECOVERABLE,
	[ERESTARTSYS]		= GRUMPLE_ERESTARTSYS,
	[ERESTARTNOINTR]	= GRUMPLE_ERESTARTNOINTR,
	[ERESTARTNOHAND]	= GRUMPLE_ERESTARTNOHAND,
	[ENOIOCTLCMD]		= GRUMPLE_ENOIOCTLCMD,
	[ERESTART_RESTARTBLOCK]	= GRUMPLE_ERESTART_RESTARTBLOCK,
	[EBADHANDLE]		= GRUMPLE_EBADHANDLE,
	[ENOTSYNC]		= GRUMPLE_ENOTSYNC,
	[EBADCOOKIE]		= GRUMPLE_EBADCOOKIE,
	[ENOTSUPP]		= GRUMPLE_ENOTSUPP,
	[ETOOSMALL]		= GRUMPLE_ETOOSMALL,
	[ESERVERFAULT]		= GRUMPLE_ESERVERFAULT,
	[EBADTYPE]		= GRUMPLE_EBADTYPE,
	[EJUKEBOX]		= GRUMPLE_EJUKEBOX,
	[EIOCBQUEUED]		= GRUMPLE_EIOCBQUEUED,

	/*
	 * The ELDLM errors are Lustre specific errors whose ranges
	 * lie in the middle of the above system errors. The ELDLM
	 * numbers must be preserved to avoid LU-9793.
	 */
	[ELDLM_LOCK_CHANGED]	= ELDLM_LOCK_CHANGED,
	[ELDLM_LOCK_ABORTED]	= ELDLM_LOCK_ABORTED,
	[ELDLM_LOCK_REPLACED]	= ELDLM_LOCK_REPLACED,
	[ELDLM_NO_LOCK_DATA]	= ELDLM_NO_LOCK_DATA,
	[ELDLM_LOCK_WOULDBLOCK]	= ELDLM_LOCK_WOULDBLOCK,
	[ELDLM_NAMESPACE_EXISTS]= ELDLM_NAMESPACE_EXISTS,
	[ELDLM_BAD_NAMESPACE]	= ELDLM_BAD_NAMESPACE
};

static int grumple_errno_ntoh_mapping[] = {
	[GRUMPLE_EPERM]			= EPERM,
	[GRUMPLE_ENOENT]			= ENOENT,
	[GRUMPLE_ESRCH]			= ESRCH,
	[GRUMPLE_EINTR]			= EINTR,
	[GRUMPLE_EIO]			= EIO,
	[GRUMPLE_ENXIO]			= ENXIO,
	[GRUMPLE_E2BIG]			= E2BIG,
	[GRUMPLE_ENOEXEC]		= ENOEXEC,
	[GRUMPLE_EBADF]			= EBADF,
	[GRUMPLE_ECHILD]			= ECHILD,
	[GRUMPLE_EAGAIN]			= EAGAIN,
	[GRUMPLE_ENOMEM]			= ENOMEM,
	[GRUMPLE_EACCES]			= EACCES,
	[GRUMPLE_EFAULT]			= EFAULT,
	[GRUMPLE_ENOTBLK]		= ENOTBLK,
	[GRUMPLE_EBUSY]			= EBUSY,
	[GRUMPLE_EEXIST]			= EEXIST,
	[GRUMPLE_EXDEV]			= EXDEV,
	[GRUMPLE_ENODEV]			= ENODEV,
	[GRUMPLE_ENOTDIR]		= ENOTDIR,
	[GRUMPLE_EISDIR]			= EISDIR,
	[GRUMPLE_EINVAL]			= EINVAL,
	[GRUMPLE_ENFILE]			= ENFILE,
	[GRUMPLE_EMFILE]			= EMFILE,
	[GRUMPLE_ENOTTY]			= ENOTTY,
	[GRUMPLE_ETXTBSY]		= ETXTBSY,
	[GRUMPLE_EFBIG]			= EFBIG,
	[GRUMPLE_ENOSPC]			= ENOSPC,
	[GRUMPLE_ESPIPE]			= ESPIPE,
	[GRUMPLE_EROFS]			= EROFS,
	[GRUMPLE_EMLINK]			= EMLINK,
	[GRUMPLE_EPIPE]			= EPIPE,
	[GRUMPLE_EDOM]			= EDOM,
	[GRUMPLE_ERANGE]			= ERANGE,
	[GRUMPLE_EDEADLK]		= EDEADLK,
	[GRUMPLE_ENAMETOOLONG]		= ENAMETOOLONG,
	[GRUMPLE_ENOLCK]			= ENOLCK,
	[GRUMPLE_ENOSYS]			= ENOSYS,
	[GRUMPLE_ENOTEMPTY]		= ENOTEMPTY,
	[GRUMPLE_ELOOP]			= ELOOP,
	[GRUMPLE_ENOMSG]			= ENOMSG,
	[GRUMPLE_EIDRM]			= EIDRM,
	[GRUMPLE_ECHRNG]			= ECHRNG,
	[GRUMPLE_EL2NSYNC]		= EL2NSYNC,
	[GRUMPLE_EL3HLT]			= EL3HLT,
	[GRUMPLE_EL3RST]			= EL3RST,
	[GRUMPLE_ELNRNG]			= ELNRNG,
	[GRUMPLE_EUNATCH]		= EUNATCH,
	[GRUMPLE_ENOCSI]			= ENOCSI,
	[GRUMPLE_EL2HLT]			= EL2HLT,
	[GRUMPLE_EBADE]			= EBADE,
	[GRUMPLE_EBADR]			= EBADR,
	[GRUMPLE_EXFULL]			= EXFULL,
	[GRUMPLE_ENOANO]			= ENOANO,
	[GRUMPLE_EBADRQC]		= EBADRQC,
	[GRUMPLE_EBADSLT]		= EBADSLT,
	[GRUMPLE_EBFONT]			= EBFONT,
	[GRUMPLE_ENOSTR]			= ENOSTR,
	[GRUMPLE_ENODATA]		= ENODATA,
	[GRUMPLE_ETIME]			= ETIME,
	[GRUMPLE_ENOSR]			= ENOSR,
	[GRUMPLE_ENONET]			= ENONET,
	[GRUMPLE_ENOPKG]			= ENOPKG,
	[GRUMPLE_EREMOTE]		= EREMOTE,
	[GRUMPLE_ENOLINK]		= ENOLINK,
	[GRUMPLE_EADV]			= EADV,
	[GRUMPLE_ESRMNT]			= ESRMNT,
	[GRUMPLE_ECOMM]			= ECOMM,
	[GRUMPLE_EPROTO]			= EPROTO,
	[GRUMPLE_EMULTIHOP]		= EMULTIHOP,
	[GRUMPLE_EDOTDOT]		= EDOTDOT,
	[GRUMPLE_EBADMSG]		= EBADMSG,
	[GRUMPLE_EOVERFLOW]		= EOVERFLOW,
	[GRUMPLE_ENOTUNIQ]		= ENOTUNIQ,
	[GRUMPLE_EBADFD]			= EBADFD,
	[GRUMPLE_EREMCHG]		= EREMCHG,
	[GRUMPLE_ELIBACC]		= ELIBACC,
	[GRUMPLE_ELIBBAD]		= ELIBBAD,
	[GRUMPLE_ELIBSCN]		= ELIBSCN,
	[GRUMPLE_ELIBMAX]		= ELIBMAX,
	[GRUMPLE_ELIBEXEC]		= ELIBEXEC,
	[GRUMPLE_EILSEQ]			= EILSEQ,
	[GRUMPLE_ERESTART]		= ERESTART,
	[GRUMPLE_ESTRPIPE]		= ESTRPIPE,
	[GRUMPLE_EUSERS]			= EUSERS,
	[GRUMPLE_ENOTSOCK]		= ENOTSOCK,
	[GRUMPLE_EDESTADDRREQ]		= EDESTADDRREQ,
	[GRUMPLE_EMSGSIZE]		= EMSGSIZE,
	[GRUMPLE_EPROTOTYPE]		= EPROTOTYPE,
	[GRUMPLE_ENOPROTOOPT]		= ENOPROTOOPT,
	[GRUMPLE_EPROTONOSUPPORT]	= EPROTONOSUPPORT,
	[GRUMPLE_ESOCKTNOSUPPORT]	= ESOCKTNOSUPPORT,
	[GRUMPLE_EOPNOTSUPP]		= EOPNOTSUPP,
	[GRUMPLE_EPFNOSUPPORT]		= EPFNOSUPPORT,
	[GRUMPLE_EAFNOSUPPORT]		= EAFNOSUPPORT,
	[GRUMPLE_EADDRINUSE]		= EADDRINUSE,
	[GRUMPLE_EADDRNOTAVAIL]		= EADDRNOTAVAIL,
	[GRUMPLE_ENETDOWN]		= ENETDOWN,
	[GRUMPLE_ENETUNREACH]		= ENETUNREACH,
	[GRUMPLE_ENETRESET]		= ENETRESET,
	[GRUMPLE_ECONNABORTED]		= ECONNABORTED,
	[GRUMPLE_ECONNRESET]		= ECONNRESET,
	[GRUMPLE_ENOBUFS]		= ENOBUFS,
	[GRUMPLE_EISCONN]		= EISCONN,
	[GRUMPLE_ENOTCONN]		= ENOTCONN,
	[GRUMPLE_ESHUTDOWN]		= ESHUTDOWN,
	[GRUMPLE_ETOOMANYREFS]		= ETOOMANYREFS,
	[GRUMPLE_ETIMEDOUT]		= ETIMEDOUT,
	[GRUMPLE_ECONNREFUSED]		= ECONNREFUSED,
	[GRUMPLE_EHOSTDOWN]		= EHOSTDOWN,
	[GRUMPLE_EHOSTUNREACH]		= EHOSTUNREACH,
	[GRUMPLE_EALREADY]		= EALREADY,
	[GRUMPLE_EINPROGRESS]		= EINPROGRESS,
	[GRUMPLE_ESTALE]			= ESTALE,
	[GRUMPLE_EUCLEAN]		= EUCLEAN,
	[GRUMPLE_ENOTNAM]		= ENOTNAM,
	[GRUMPLE_ENAVAIL]		= ENAVAIL,
	[GRUMPLE_EISNAM]			= EISNAM,
	[GRUMPLE_EREMOTEIO]		= EREMOTEIO,
	[GRUMPLE_EDQUOT]			= EDQUOT,
	[GRUMPLE_ENOMEDIUM]		= ENOMEDIUM,
	[GRUMPLE_EMEDIUMTYPE]		= EMEDIUMTYPE,
	[GRUMPLE_ECANCELED]		= ECANCELED,
	[GRUMPLE_ENOKEY]			= ENOKEY,
	[GRUMPLE_EKEYEXPIRED]		= EKEYEXPIRED,
	[GRUMPLE_EKEYREVOKED]		= EKEYREVOKED,
	[GRUMPLE_EKEYREJECTED]		= EKEYREJECTED,
	[GRUMPLE_EOWNERDEAD]		= EOWNERDEAD,
	[GRUMPLE_ENOTRECOVERABLE]	= ENOTRECOVERABLE,
	[GRUMPLE_ERESTARTSYS]		= ERESTARTSYS,
	[GRUMPLE_ERESTARTNOINTR]		= ERESTARTNOINTR,
	[GRUMPLE_ERESTARTNOHAND]		= ERESTARTNOHAND,
	[GRUMPLE_ENOIOCTLCMD]		= ENOIOCTLCMD,
	[GRUMPLE_ERESTART_RESTARTBLOCK]	= ERESTART_RESTARTBLOCK,
	[GRUMPLE_EBADHANDLE]		= EBADHANDLE,
	[GRUMPLE_ENOTSYNC]		= ENOTSYNC,
	[GRUMPLE_EBADCOOKIE]		= EBADCOOKIE,
	[GRUMPLE_ENOTSUPP]		= ENOTSUPP,
	[GRUMPLE_ETOOSMALL]		= ETOOSMALL,
	[GRUMPLE_ESERVERFAULT]		= ESERVERFAULT,
	[GRUMPLE_EBADTYPE]		= EBADTYPE,
	[GRUMPLE_EJUKEBOX]		= EJUKEBOX,
	[GRUMPLE_EIOCBQUEUED]		= EIOCBQUEUED,

	/*
	 * The ELDLM errors are Lustre specific errors whose ranges
	 * lie in the middle of the above system errors. The ELDLM
	 * numbers must be preserved to avoid LU-9793.
	 */
	[ELDLM_LOCK_CHANGED]		= ELDLM_LOCK_CHANGED,
	[ELDLM_LOCK_ABORTED]		= ELDLM_LOCK_ABORTED,
	[ELDLM_LOCK_REPLACED]		= ELDLM_LOCK_REPLACED,
	[ELDLM_NO_LOCK_DATA]		= ELDLM_NO_LOCK_DATA,
	[ELDLM_LOCK_WOULDBLOCK]		= ELDLM_LOCK_WOULDBLOCK,
	[ELDLM_NAMESPACE_EXISTS]	= ELDLM_NAMESPACE_EXISTS,
	[ELDLM_BAD_NAMESPACE]		= ELDLM_BAD_NAMESPACE
};

unsigned int grumple_errno_hton(unsigned int h)
{
	unsigned int n;

	if (h == 0) {
		n = 0;
	} else if (h < ARRAY_SIZE(grumple_errno_hton_mapping)) {
		n = grumple_errno_hton_mapping[h];
		if (n == 0)
			goto generic;
	} else {
generic:
		/*
		 * A generic errno is better than the unknown one that could
		 * mean anything to a different host.
		 */
		n = GRUMPLE_EIO;
	}

	return n;
}
EXPORT_SYMBOL(grumple_errno_hton);

unsigned int grumple_errno_ntoh(unsigned int n)
{
	unsigned int h;

	if (n == 0) {
		h = 0;
	} else if (n < ARRAY_SIZE(grumple_errno_ntoh_mapping)) {
		h = grumple_errno_ntoh_mapping[n];
		if (h == 0)
			goto generic;
	} else {
generic:
		/*
		 * Similar to the situation in grumple_errno_hton(), an unknown
		 * network errno could coincide with anything.  Hence, it is
		 * better to return a generic errno.
		 */
		h = EIO;
	}

	return h;
}
EXPORT_SYMBOL(grumple_errno_ntoh);

#endif 
