EXTRA_DIST  = grumple-build.m4 grumple-build-linux.m4
EXTRA_DIST += grumple-build-ldiskfs.m4 grumple-build-zfs.m4
EXTRA_DIST += grumple-toolchain.m4 grumple-compiler-plugins.m4
EXTRA_DIST += grumple-core.m4 kerberos5.m4 ac_pkg_swig.m4
EXTRA_DIST += ac_python_devel.m4 grumple-lnet.m4
EXTRA_DIST += grumple-libcfs.m4
