grumpleincludedir = /usr/include/linux/grumple
grumpleinclude_HEADERS = \
	grumple_cfg.h \
	grumple_fid.h \
	grumple_fiemap.h \
	grumple_idl.h \
	grumple_ioctl.h \
	lgss.h \
	grumple_kernelcomm.h \
	grumple_ostid.h \
	grumple_param.h \
	grumple_user.h \
	grumple_ver.h
if SERVER
grumpleinclude_HEADERS += \
	grumple_access_log.h \
	grumple_barrier_user.h \
	grumple_disk.h \
	grumple_lfsck_user.h \
	grumple_log_user.h
endif
EXTRA_DIST = \
	grumple_access_log.h \
	grumple_barrier_user.h \
	grumple_cfg.h \
	grumple_disk.h \
	grumple_fid.h \
	grumple_fiemap.h \
	grumple_idl.h \
	grumple_ioctl.h \
	lgss.h \
	grumple_kernelcomm.h \
	grumple_lfsck_user.h \
	grumple_log_user.h \
	grumple_ostid.h \
	grumple_param.h \
	grumple_user.h \
	grumple_ver.h
