SUBDIRS = grumple uapi/linux/grumple
DIST_SUBDIRS = grumple uapi/linux/grumple
EXTRA_DIST = \
	cfs_hash.h \
	cl_object.h \
	dt_object.h \
	erasure_code.h \
	llog_swab.h \
	lprocfs_status.h \
	lu_object.h \
	grumple_acl.h \
	grumple_barrier.h \
	grumple_compat.h \
	grumple_crypto.h \
	grumple_disk.h \
	grumple_dlm_flags.h \
	grumple_dlm.h \
	grumple_errno.h \
	grumple_export.h \
	grumple_fid.h \
	grumple_fld.h \
	grumple_ha.h \
	grumple_handles.h \
	grumple_idmap.h \
	grumple_import.h \
	grumple_intent.h \
	grumple_ioctl_old.h \
	grumple_lfsck.h \
	grumple_lib.h \
	grumple_linkea.h \
	grumple_lmv.h \
	grumple_log.h \
	grumple_mdc.h \
	grumple_mds.h \
	grumple_net.h \
	grumple_osc.h \
	grumple_nodemap.h \
	grumple_nrs.h \
	grumple_nrs_crr.h \
	grumple_nrs_delay.h \
	grumple_nrs_fifo.h \
	grumple_nrs_orr.h \
	grumple_nrs_tbf.h \
	grumple_obdo.h \
	grumple_quota.h \
	grumple_req_layout.h \
	grumple_scrub.h \
	grumple_sec.h \
	grumple_swab.h \
	grumple_update.h \
	lu_target.h \
	lvfs.h \
	md_object.h \
	obd_cksum.h \
	obd_class.h \
	obd.h \
	obd_support.h \
	obd_target.h \
	obj_update.h \
	range_lock.h \
	upcall_cache.h \
	grumple_kernelcomm.h \
	seq_range.h
